// Entries and Replies
// Generated by CANopen Architect Standard 4.61.4043 on 3/20/2016 11:12:12 PM
// Generated from project C:\cd\ULC\build\ULC-build\NICBOT_MAIN_APP\APP\CANopen\MCO_NICBOTMAIN__User\EDS\NIC_Main.cax
// Generated from EDS 'NIC_Main' 01-27-2016 09:08AM by Unknown
// Use with MicroCANopen Plus CANopen stack
// For more information visit www.esacademy.com and www.microcanopen.com

// Check for warnings below before using this file

#ifndef _ENTRIESANDREPLIESH_
#define _ENTRIESANDREPLIESH_

// Define IGNORE_AUTO_SERIAL if the application or stack defines the serial number

#ifndef IGNORE_AUTO_SERIAL
#define SDOREPLYSERIAL(index,sub,len,val) SDOREPLY(index,sub,len,val)
#else
#define SDOREPLYSERIAL(index,sub,len,val)
#endif

// WARNING - below is a best guess as to which entries are really constants
// Comment out entries that are changed by the application/stack

#define SDOREPLY_ENTRIES \
/* [0x1000,0x00] Device Type (Unsigned32) */ \
SDOREPLY(0x1000, 0x00, 4, OD_DEVICE_TYPE), \
/* [0x1005,0x00] SYNC COB-ID (Unsigned32) */ \
SDOREPLY(0x1005, 0x00, 4, 0x00000080L), \
/* [0x1008,0x00] Manufacturer Device Name (VisibleString) */ \
SDOREPLY(0x1008, 0x00, 4, 0x4E49414DL), \
/* [0x1009,0x00] Manufacturer Hardware Version (VisibleString) */ \
SDOREPLY(0x1009, 0x00, 4, 0x30302E31L), \
/* [0x100A,0x00] Manufacturer Software Version (VisibleString) */ \
SDOREPLY(0x100A, 0x00, 4, 0x30302E31L), \
/* [0x1011,0x00] Restore Default Parameters - Number of Entries (Unsigned8) */ \
SDOREPLY(0x1011, 0x00, 1, 0x00000004L), \
/* [0x1014,0x00] Emergency COB-ID (Unsigned32) */ \
SDOREPLY(0x1014, 0x00, 4, DEFAULT_EMCY_COBID), \
/* [0x1016,0x00] Consumer Heartbeat Time - Number of Entries (Unsigned8) */ \
SDOREPLY(0x1016, 0x00, 1, 0x00000001L), \
/* [0x1018,0x00] Identity - Number of Entries (Unsigned8) */ \
SDOREPLY(0x1018, 0x00, 1, 0x00000001L), \
/* [0x1018,0x01] Identity - Vendor ID (Unsigned32) */ \
SDOREPLY(0x1018, 0x01, 4, OD_VENDOR_ID), \
\
/* PDO parameters are in Object Dictionary */ \
\
/* RPDO communication parameters */ \
/* [0x1400,0x00] Receive PDO Parameter 1 - Highest Subindex Supported (Unsigned8) */ \
SDOREPLY(0x1400, 0x00, 1, 0x00000002L), \
/* [0x1400,0x01] Receive PDO Parameter 1 - COB ID used by PDO (Unsigned32) */ \
SDOREPLY(0x1400, 0x01, 4, 0x00000000L), \
/* [0x1400,0x02] Receive PDO Parameter 1 - Transmission Type (Unsigned8) */ \
SDOREPLY(0x1400, 0x02, 1, 0x000000FFL), \
/* [0x1400,0x03] Receive PDO Parameter 1 - Transmission Type (Unsigned8) */ \
SDOREPLY(0x1400, 0x03, 1, 0x000000FFL), \
\
/* RPDO mapping parameters */ \
/* [0x1600,0x00] Receive PDO Mapping 1 - Number of Entries (Unsigned8) */ \
SDOREPLY(0x1600, 0x00, 1, 0x00000002L), \
/* [0x1600,0x01] Receive PDO Mapping 1 - Target Velocity (Unsigned32) */ \
SDOREPLY(0x1600, 0x01, 4, 0x60FF0020L), \
/* [0x1600,0x02] Receive PDO Mapping 1 - Target Torque (Unsigned32) */ \
SDOREPLY(0x1600, 0x02, 4, 0x60710010L), \
/* [0x1600,0x03] Receive PDO Mapping 1 - Target Torque (Unsigned32) */ \
SDOREPLY(0x1600, 0x03, 4, 0x60710010L), \
\
/* TPDO communication parameters */ \
/* [0x1800,0x00] Transmit PDO Parameter 1 - Highest Subindex Supported (Unsigned8) */ \
SDOREPLY(0x1800, 0x00, 1, 0x00000005L), \
/* [0x1800,0x01] Transmit PDO Parameter 1 - COB ID used by PDO (Unsigned32) */ \
SDOREPLY(0x1800, 0x01, 4, 0x00000000L), \
/* [0x1800,0x02] Transmit PDO Parameter 1 - Transmission Type (Unsigned8) */ \
SDOREPLY(0x1800, 0x02, 1, 0x000000FFL), \
/* [0x1800,0x03] Transmit PDO Parameter 1 - Inhibit Time (Unsigned16) */ \
SDOREPLY(0x1800, 0x03, 2, 0x00000000L), \
/* [0x1800,0x04] Transmit PDO Parameter 1 - Compatibility Entry (Unsigned8) */ \
SDOREPLY(0x1800, 0x04, 1, 0x00000000L), \
/* [0x1800,0x05] Transmit PDO Parameter 1 - Event Timer (Unsigned16) */ \
SDOREPLY(0x1800, 0x05, 2, 0x00000000L), \
/* [0x1801,0x00] Transmit PDO Parameter 2 - Highest Subindex Supported (Unsigned8) */ \
SDOREPLY(0x1801, 0x00, 1, 0x00000005L), \
/* [0x1801,0x01] Transmit PDO Parameter 2 - COB ID used by PDO (Unsigned32) */ \
SDOREPLY(0x1801, 0x01, 4, 0x00000000L), \
/* [0x1801,0x02] Transmit PDO Parameter 2 - Transmission Type (Unsigned8) */ \
SDOREPLY(0x1801, 0x02, 1, 0x000000FFL), \
/* [0x1801,0x03] Transmit PDO Parameter 2 - Inhibit Time (Unsigned16) */ \
SDOREPLY(0x1801, 0x03, 2, 0x00000000L), \
/* [0x1801,0x04] Transmit PDO Parameter 2 - Compatibility Entry (Unsigned8) */ \
SDOREPLY(0x1801, 0x04, 1, 0x00000000L), \
/* [0x1801,0x05] Transmit PDO Parameter 2 - Event Timer (Unsigned16) */ \
SDOREPLY(0x1801, 0x05, 2, 0x00000000L), \
/* [0x1802,0x00] Transmit PDO Parameter 3 - Highest Subindex Supported (Unsigned8) */ \
SDOREPLY(0x1802, 0x00, 1, 0x00000005L), \
/* [0x1802,0x01] Transmit PDO Parameter 3 - COB ID used by PDO (Unsigned32) */ \
SDOREPLY(0x1802, 0x01, 4, 0x00000000L), \
/* [0x1802,0x02] Transmit PDO Parameter 3 - Transmission Type (Unsigned8) */ \
SDOREPLY(0x1802, 0x02, 1, 0x000000FFL), \
/* [0x1802,0x03] Transmit PDO Parameter 3 - Inhibit Time (Unsigned16) */ \
SDOREPLY(0x1802, 0x03, 2, 0x00000000L), \
/* [0x1802,0x04] Transmit PDO Parameter 3 - Compatibility Entry (Unsigned8) */ \
SDOREPLY(0x1802, 0x04, 1, 0x00000000L), \
/* [0x1802,0x05] Transmit PDO Parameter 3 - Event Timer (Unsigned16) */ \
SDOREPLY(0x1802, 0x05, 2, 0x00000000L), \
/* [0x1803,0x00] Transmit PDO Parameter 4 - Highest Subindex Supported (Unsigned8) */ \
SDOREPLY(0x1803, 0x00, 1, 0x00000005L), \
/* [0x1803,0x01] Transmit PDO Parameter 4 - COB ID used by PDO (Unsigned32) */ \
SDOREPLY(0x1803, 0x01, 4, 0x00000000L), \
/* [0x1803,0x02] Transmit PDO Parameter 4 - Transmission Type (Unsigned8) */ \
SDOREPLY(0x1803, 0x02, 1, 0x000000FFL), \
/* [0x1803,0x03] Transmit PDO Parameter 4 - Inhibit Time (Unsigned16) */ \
SDOREPLY(0x1803, 0x03, 2, 0x00000000L), \
/* [0x1803,0x04] Transmit PDO Parameter 4 - Compatibility Entry (Unsigned8) */ \
SDOREPLY(0x1803, 0x04, 1, 0x00000000L), \
/* [0x1803,0x05] Transmit PDO Parameter 4 - Event Timer (Unsigned16) */ \
SDOREPLY(0x1803, 0x05, 2, 0x00000000L), \
\
/* TPDO mapping parameters */ \
/* [0x1A00,0x00] Transmit PDO Mapping 1 - Number of Active Entries (Unsigned8) */ \
SDOREPLY(0x1A00, 0x00, 1, 0x00000000L), \
/* [0x1A00,0x01] Transmit PDO Mapping 1 - Map 1 (Unsigned32) */ \
SDOREPLY(0x1A00, 0x01, 4, 0x00000000L), \
/* [0x1A00,0x02] Transmit PDO Mapping 1 - Map 2 (Unsigned32) */ \
SDOREPLY(0x1A00, 0x02, 4, 0x00000000L), \
/* [0x1A00,0x03] Transmit PDO Mapping 1 - Map 3 (Unsigned32) */ \
SDOREPLY(0x1A00, 0x03, 4, 0x00000000L), \
/* [0x1A00,0x04] Transmit PDO Mapping 1 - Map 4 (Unsigned32) */ \
SDOREPLY(0x1A00, 0x04, 4, 0x00000000L), \
/* [0x1A00,0x05] Transmit PDO Mapping 1 - Map 5 (Unsigned32) */ \
SDOREPLY(0x1A00, 0x05, 4, 0x00000000L), \
/* [0x1A00,0x06] Transmit PDO Mapping 1 - Map 6 (Unsigned32) */ \
SDOREPLY(0x1A00, 0x06, 4, 0x00000000L), \
/* [0x1A00,0x07] Transmit PDO Mapping 1 - Map 7 (Unsigned32) */ \
SDOREPLY(0x1A00, 0x07, 4, 0x00000000L), \
/* [0x1A00,0x08] Transmit PDO Mapping 1 - Map 8 (Unsigned32) */ \
SDOREPLY(0x1A00, 0x08, 4, 0x00000000L), \
/* [0x1A01,0x00] Transmit PDO Mapping 2 - Number of Active Entries (Unsigned8) */ \
SDOREPLY(0x1A01, 0x00, 1, 0x00000000L), \
/* [0x1A01,0x01] Transmit PDO Mapping 2 - Map 1 (Unsigned32) */ \
SDOREPLY(0x1A01, 0x01, 4, 0x00000000L), \
/* [0x1A01,0x02] Transmit PDO Mapping 2 - Map 2 (Unsigned32) */ \
SDOREPLY(0x1A01, 0x02, 4, 0x00000000L), \
/* [0x1A01,0x03] Transmit PDO Mapping 2 - Map 3 (Unsigned32) */ \
SDOREPLY(0x1A01, 0x03, 4, 0x00000000L), \
/* [0x1A01,0x04] Transmit PDO Mapping 2 - Map 4 (Unsigned32) */ \
SDOREPLY(0x1A01, 0x04, 4, 0x00000000L), \
/* [0x1A01,0x05] Transmit PDO Mapping 2 - Map 5 (Unsigned32) */ \
SDOREPLY(0x1A01, 0x05, 4, 0x00000000L), \
/* [0x1A01,0x06] Transmit PDO Mapping 2 - Map 6 (Unsigned32) */ \
SDOREPLY(0x1A01, 0x06, 4, 0x00000000L), \
/* [0x1A01,0x07] Transmit PDO Mapping 2 - Map 7 (Unsigned32) */ \
SDOREPLY(0x1A01, 0x07, 4, 0x00000000L), \
/* [0x1A01,0x08] Transmit PDO Mapping 2 - Map 8 (Unsigned32) */ \
SDOREPLY(0x1A01, 0x08, 4, 0x00000000L), \
/* [0x1A02,0x00] Transmit PDO Mapping 3 - Number of Active Entries (Unsigned8) */ \
SDOREPLY(0x1A02, 0x00, 1, 0x00000000L), \
/* [0x1A02,0x01] Transmit PDO Mapping 3 - Map 1 (Unsigned32) */ \
SDOREPLY(0x1A02, 0x01, 4, 0x00000000L), \
/* [0x1A02,0x02] Transmit PDO Mapping 3 - Map 2 (Unsigned32) */ \
SDOREPLY(0x1A02, 0x02, 4, 0x00000000L), \
/* [0x1A02,0x03] Transmit PDO Mapping 3 - Map 3 (Unsigned32) */ \
SDOREPLY(0x1A02, 0x03, 4, 0x00000000L), \
/* [0x1A02,0x04] Transmit PDO Mapping 3 - Map 4 (Unsigned32) */ \
SDOREPLY(0x1A02, 0x04, 4, 0x00000000L), \
/* [0x1A02,0x05] Transmit PDO Mapping 3 - Map 5 (Unsigned32) */ \
SDOREPLY(0x1A02, 0x05, 4, 0x00000000L), \
/* [0x1A02,0x06] Transmit PDO Mapping 3 - Map 6 (Unsigned32) */ \
SDOREPLY(0x1A02, 0x06, 4, 0x00000000L), \
/* [0x1A02,0x07] Transmit PDO Mapping 3 - Map 7 (Unsigned32) */ \
SDOREPLY(0x1A02, 0x07, 4, 0x00000000L), \
/* [0x1A02,0x08] Transmit PDO Mapping 3 - Map 8 (Unsigned32) */ \
SDOREPLY(0x1A02, 0x08, 4, 0x00000000L), \
/* [0x1A03,0x00] Transmit PDO Mapping 4 - Number of Active Entries (Unsigned8) */ \
SDOREPLY(0x1A03, 0x00, 1, 0x00000000L), \
/* [0x1A03,0x01] Transmit PDO Mapping 4 - Map 1 (Unsigned32) */ \
SDOREPLY(0x1A03, 0x01, 4, 0x00000000L), \
/* [0x1A03,0x02] Transmit PDO Mapping 4 - Map 2 (Unsigned32) */ \
SDOREPLY(0x1A03, 0x02, 4, 0x00000000L), \
/* [0x1A03,0x03] Transmit PDO Mapping 4 - Map 3 (Unsigned32) */ \
SDOREPLY(0x1A03, 0x03, 4, 0x00000000L), \
/* [0x1A03,0x04] Transmit PDO Mapping 4 - Map 4 (Unsigned32) */ \
SDOREPLY(0x1A03, 0x04, 4, 0x00000000L), \
/* [0x1A03,0x05] Transmit PDO Mapping 4 - Map 5 (Unsigned32) */ \
SDOREPLY(0x1A03, 0x05, 4, 0x00000000L), \
/* [0x1A03,0x06] Transmit PDO Mapping 4 - Map 6 (Unsigned32) */ \
SDOREPLY(0x1A03, 0x06, 4, 0x00000000L), \
/* [0x1A03,0x07] Transmit PDO Mapping 4 - Map 7 (Unsigned32) */ \
SDOREPLY(0x1A03, 0x07, 4, 0x00000000L), \
/* [0x1A03,0x08] Transmit PDO Mapping 4 - Map 8 (Unsigned32) */ \
SDOREPLY(0x1A03, 0x08, 4, 0x00000000L), \
\
/* [0x1F50,0x00] Download Program Data - Number of Entries (Unsigned8) */ \
SDOREPLY(0x1F50, 0x00, 1, 0x00000001L), \
/* [0x1F51,0x00] Program Control - Number of Entries (Unsigned8) */ \
SDOREPLY(0x1F51, 0x00, 1, 0x00000001L), \
/* [0x1F51,0x01] Program Control - Control Program 1 (Unsigned8) */ \
SDOREPLY(0x1F51, 0x01, 1, 0x00000000L), \
/* [0x1F80,0x00] NMT Startup (Unsigned32) */ \
SDOREPLY(0x1F80, 0x00, 4, 0x00000000L), \

// 1 MACROS WERE GENERATED TO HOLD THE SDO REPLIES
// USE THE FOLLOWING INITIALIZER:
// SDOREPLY_ENTRIES 


#define ODGENTRY_CONSTINITS \
/* WARNING - ENTRY [1F50,01] SKIPPED AS DATA SIZE IS UNKNOWN */ \


#define ODGENTRY_ENTRIES \
/* WARNING - ENTRY [1F50,01] SKIPPED AS DATA SIZE IS UNKNOWN */ \

// 1 MACROS WERE GENERATED TO HOLD THE OD REPLIES
// USE THE FOLLOWING INITIALIZER:
// ODGENTRY_ENTRIES 

#define ODENTRY_ENTRIES \
/* WARNING - ENTRY [60FF,00] NOT FOUND IN EDS/DCF */ \
/* WARNING - ENTRY [6071,00] NOT FOUND IN EDS/DCF */ \
/* WARNING - ENTRY [6071,00] NOT FOUND IN EDS/DCF */ \
ODENTRY(0x1001, 0x00, 1+ODRD+RMAP, P100100_ERROR_REGISTER), \
ODENTRY(0x1011, 0x01, 4+ODRD, P101101_RESTORE_ALL_PARAMETERS), \
ODENTRY(0x1011, 0x02, 4+ODRD, P101102_RESTORE_COMMUNICATION_PARAMETERS), \
ODENTRY(0x1011, 0x03, 4+ODRD, P101103_RESTORE_APPLICATION_PARAMETERS), \
ODENTRY(0x1011, 0x04, 4+ODRD, P101104_RESTORE_MANUFACTURER_DEFINED_PARAMETERS_1), \
ODENTRY(0x1015, 0x00, 2+ODRD+ODWR, P101500_EMERGENCY_INHIBIT_TIME), \
ODENTRY(0x1016, 0x01, 4+ODRD+ODWR, P101601_CONSUMER_HEARTBEAT_TIME_1), \
ODENTRY(0x1017, 0x00, 2+ODRD+ODWR, P101700_PRODUCER_HEARTBEAT_TIME), \
ODENTRY(0x1800, 0x02, 1+ODRD+ODWR, P180002_TRANSMISSION_TYPE), \
ODENTRY(0x1800, 0x03, 2+ODRD+ODWR, P180003_INHIBIT_TIME), \
ODENTRY(0x1800, 0x05, 2+ODRD+ODWR, P180005_EVENT_TIMER), \
ODENTRY(0x1801, 0x02, 1+ODRD+ODWR, P180102_TRANSMISSION_TYPE), \
ODENTRY(0x1801, 0x03, 2+ODRD+ODWR, P180103_INHIBIT_TIME), \
ODENTRY(0x1801, 0x05, 2+ODRD+ODWR, P180105_EVENT_TIMER), \
ODENTRY(0x1802, 0x02, 1+ODRD+ODWR, P180202_TRANSMISSION_TYPE), \
ODENTRY(0x1802, 0x03, 2+ODRD+ODWR, P180203_INHIBIT_TIME), \
ODENTRY(0x1802, 0x05, 2+ODRD+ODWR, P180205_EVENT_TIMER), \
ODENTRY(0x1803, 0x02, 1+ODRD+ODWR, P180302_TRANSMISSION_TYPE), \
ODENTRY(0x1803, 0x03, 2+ODRD+ODWR, P180303_INHIBIT_TIME), \
ODENTRY(0x1803, 0x05, 2+ODRD+ODWR, P180305_EVENT_TIMER), \
ODENTRY(0x1A00, 0x00, 1+ODRD+ODWR, P1A0000_NUMBER_OF_ACTIVE_ENTRIES), \
ODENTRY(0x1A00, 0x01, 4+ODRD+ODWR, P1A0001_MAP_1), \
ODENTRY(0x1A00, 0x02, 4+ODRD+ODWR, P1A0002_MAP_2), \
ODENTRY(0x1A00, 0x03, 4+ODRD+ODWR, P1A0003_MAP_3), \
ODENTRY(0x1A00, 0x04, 4+ODRD+ODWR, P1A0004_MAP_4), \
ODENTRY(0x1A00, 0x05, 4+ODRD+ODWR, P1A0005_MAP_5), \
ODENTRY(0x1A00, 0x06, 4+ODRD+ODWR, P1A0006_MAP_6), \
ODENTRY(0x1A00, 0x07, 4+ODRD+ODWR, P1A0007_MAP_7), \
ODENTRY(0x1A00, 0x08, 4+ODRD+ODWR, P1A0008_MAP_8), \
ODENTRY(0x1A01, 0x00, 1+ODRD+ODWR, P1A0100_NUMBER_OF_ACTIVE_ENTRIES), \
ODENTRY(0x1A01, 0x01, 4+ODRD+ODWR, P1A0101_MAP_1), \
ODENTRY(0x1A01, 0x02, 4+ODRD+ODWR, P1A0102_MAP_2), \
ODENTRY(0x1A01, 0x03, 4+ODRD+ODWR, P1A0103_MAP_3), \
ODENTRY(0x1A01, 0x04, 4+ODRD+ODWR, P1A0104_MAP_4), \
ODENTRY(0x1A01, 0x05, 4+ODRD+ODWR, P1A0105_MAP_5), \
ODENTRY(0x1A01, 0x06, 4+ODRD+ODWR, P1A0106_MAP_6), \
ODENTRY(0x1A01, 0x07, 4+ODRD+ODWR, P1A0107_MAP_7), \
ODENTRY(0x1A01, 0x08, 4+ODRD+ODWR, P1A0108_MAP_8), \
ODENTRY(0x1A02, 0x00, 1+ODRD+ODWR, P1A0200_NUMBER_OF_ACTIVE_ENTRIES), \
ODENTRY(0x1A02, 0x01, 4+ODRD+ODWR, P1A0201_MAP_1), \
ODENTRY(0x1A02, 0x02, 4+ODRD+ODWR, P1A0202_MAP_2), \
ODENTRY(0x1A02, 0x03, 4+ODRD+ODWR, P1A0203_MAP_3), \
ODENTRY(0x1A02, 0x04, 4+ODRD+ODWR, P1A0204_MAP_4), \
ODENTRY(0x1A02, 0x05, 4+ODRD+ODWR, P1A0205_MAP_5), \
ODENTRY(0x1A02, 0x06, 4+ODRD+ODWR, P1A0206_MAP_6), \
ODENTRY(0x1A02, 0x07, 4+ODRD+ODWR, P1A0207_MAP_7), \
ODENTRY(0x1A02, 0x08, 4+ODRD+ODWR, P1A0208_MAP_8), \
ODENTRY(0x1A03, 0x00, 1+ODRD+ODWR, P1A0300_NUMBER_OF_ACTIVE_ENTRIES), \
ODENTRY(0x1A03, 0x01, 4+ODRD+ODWR, P1A0301_MAP_1), \
ODENTRY(0x1A03, 0x02, 4+ODRD+ODWR, P1A0302_MAP_2), \
ODENTRY(0x1A03, 0x03, 4+ODRD+ODWR, P1A0303_MAP_3), \
ODENTRY(0x1A03, 0x04, 4+ODRD+ODWR, P1A0304_MAP_4), \
ODENTRY(0x1A03, 0x05, 4+ODRD+ODWR, P1A0305_MAP_5), \
ODENTRY(0x1A03, 0x06, 4+ODRD+ODWR, P1A0306_MAP_6), \
ODENTRY(0x1A03, 0x07, 4+ODRD+ODWR, P1A0307_MAP_7), \
ODENTRY(0x1A03, 0x08, 4+ODRD+ODWR, P1A0308_MAP_8), \
/* WARNING - ENTRY [1F50,01] SKIPPED AS DATA SIZE IS UNKNOWN */ \
ODENTRY(0x2100, 0x00, 1+ODRD+ODWR, P210000_CAN_BIT_RATE_CODE), \
ODENTRY(0x2101, 0x00, 1+ODRD+ODWR, P210100_CAN_NODE_ID), \
ODENTRY(0x2102, 0x00, 1+ODRD+ODWR, P210200_DEVICE_MODE), \
ODENTRY(0x2105, 0x00, 4+ODWR, P210500_DEVICE_STORE_PARAMETERS), \
ODENTRY(0x2301, 0x00, 1+ODRD, P230100_HIGHEST_SUBINDEX), \
ODENTRY(0x2301, 0x01, 1+ODRD+ODWR, P230101_CAMERA_SELECT_A), \
ODENTRY(0x2301, 0x02, 1+ODRD+ODWR, P230102_CAMERA_SELECT_B), \
ODENTRY(0x2303, 0x00, 1+ODRD, P230300_HIGHEST_SUBINDEX), \
ODENTRY(0x2303, 0x01, 1+ODRD+ODWR, P230301_CAMERA_1), \
ODENTRY(0x2303, 0x02, 1+ODRD+ODWR, P230302_CAMERA_2), \
ODENTRY(0x2303, 0x03, 1+ODRD+ODWR, P230303_CAMERA_3), \
ODENTRY(0x2303, 0x04, 1+ODRD+ODWR, P230304_CAMERA_4), \
ODENTRY(0x2303, 0x05, 1+ODRD+ODWR, P230305_CAMERA_5), \
ODENTRY(0x2303, 0x06, 1+ODRD+ODWR, P230306_CAMERA_6), \
ODENTRY(0x2303, 0x07, 1+ODRD+ODWR, P230307_CAMERA_7), \
ODENTRY(0x2303, 0x08, 1+ODRD+ODWR, P230308_CAMERA_8), \
ODENTRY(0x2303, 0x09, 1+ODRD+ODWR, P230309_CAMERA_9), \
ODENTRY(0x2303, 0x0A, 1+ODRD+ODWR, P23030A_CAMERA_10), \
ODENTRY(0x2303, 0x0B, 1+ODRD+ODWR, P23030B_CAMERA_11), \
ODENTRY(0x2303, 0x0C, 1+ODRD+ODWR, P23030C_CAMERA_12), \
ODENTRY(0x2304, 0x00, 2+ODRD+ODWR, P230400_SOLENOID_CONTROL), \
ODENTRY(0x2311, 0x00, 2+ODRD+ODWR, P231100_FRONT_DRILL_SPEED_SET_POINT), \
ODENTRY(0x2312, 0x00, 2+ODRD+ODWR, P231200_FRONT_DRILL_INDEX_SET_POINT), \
ODENTRY(0x2313, 0x00, 2+ODRD+ODWR, P231300_REAR_DRILL_SPEED_SET_POINT), \
ODENTRY(0x2314, 0x00, 2+ODRD+ODWR, P231400_REAR_DRILL_INDEX_SET_POINT), \
ODENTRY(0x2411, 0x00, 2+ODRD+RMAP, P241100_ACTUAL_FRONT_DRILL_SPEED), \
ODENTRY(0x2412, 0x00, 2+ODRD+RMAP, P241200_ACTUAL_FRONT_DRILL_INDEX), \
ODENTRY(0x2413, 0x00, 2+ODRD+RMAP, P241300_ACTUAL_REAR_DRILL_SPEED), \
ODENTRY(0x2414, 0x00, 2+ODRD+RMAP, P241400_ACTUAL_REAR_DRILL_INDEX), \
ODENTRY(0x2441, 0x00, 2+ODRD+RMAP, P244100_ACCELEROMETER_X_VALUE), \
ODENTRY(0x2442, 0x00, 2+ODRD+RMAP, P244200_ACCELEROMETER_Y_VALUE), \
ODENTRY(0x2443, 0x00, 2+ODRD+RMAP, P244300_ACCELEROMETER_Z_VALUE), \
ODENTRY(0x2500, 0x00, 2+ODRD+ODWR, P250000_PROCESS_CONTROL), \
ODENTRY(0x2501, 0x00, 2+ODRD+RMAP, P250100_PROCESS_STATUS), \

// 1 MACROS WERE GENERATED TO HOLD THE OD REPLIES
// USE THE FOLLOWING INITIALIZER:
// ODENTRY_ENTRIES 

#endif // _ENTRIESANDREPLIESH_
