// Entries and Replies
// Generated by CANopen Architect Standard 4.61.4043 on 3/12/2016 2:29:40 PM
// Generated from project C:\cd\ULC\build\ULC-build\NICBOT_MAIN_APP\APP\CANopen\MCO_NICBOTMAIN__User\EDS\NIC_Main.cax
// Generated from EDS 'NIC_Main' 01-27-2016 09:08AM by Unknown
// Use with MicroCANopen Plus CANopen stack
// For more information visit www.esacademy.com and www.microcanopen.com

// Check for warnings below before using this file

#ifndef _ENTRIESANDREPLIESH_
#define _ENTRIESANDREPLIESH_

// Define IGNORE_AUTO_SERIAL if the application or stack defines the serial number

#ifndef IGNORE_AUTO_SERIAL
#define SDOREPLYSERIAL(index,sub,len,val) SDOREPLY(index,sub,len,val)
#else
#define SDOREPLYSERIAL(index,sub,len,val)
#endif

// WARNING - below is a best guess as to which entries are really constants
// Comment out entries that are changed by the application/stack

#define SDOREPLY_ENTRIES \
/* [0x1000,0x00] Device Type (Unsigned32) */ \
SDOREPLY(0x1000, 0x00, 4, OD_DEVICE_TYPE), \
/* [0x1005,0x00] SYNC COB-ID (Unsigned32) */ \
SDOREPLY(0x1005, 0x00, 4, 0x00000080L), \
/* [0x1008,0x00] Manufacturer Device Name (VisibleString) */ \
SDOREPLY(0x1008, 0x00, 4, 0x004C4857L), \
/* [0x1009,0x00] Manufacturer Hardware Version (VisibleString) */ \
SDOREPLY(0x1009, 0x00, 4, 0x30302E31L), \
/* [0x100A,0x00] Manufacturer Software Version (VisibleString) */ \
SDOREPLY(0x100A, 0x00, 4, 0x30302E31L), \
/* [0x1011,0x00] Restore Default Parameters - Number of Entries (Unsigned8) */ \
SDOREPLY(0x1011, 0x00, 1, 0x00000004L), \
/* [0x1014,0x00] Emergency COB-ID (Unsigned32) */ \
SDOREPLY(0x1014, 0x00, 4, DEFAULT_EMCY_COBID), \
/* [0x1016,0x00] Consumer Heartbeat Time - Number of Entries (Unsigned8) */ \
SDOREPLY(0x1016, 0x00, 1, 0x00000001L), \
/* [0x1018,0x00] Identity - Number of Entries (Unsigned8) */ \
SDOREPLY(0x1018, 0x00, 1, 0x00000001L), \
/* [0x1018,0x01] Identity - Vendor ID (Unsigned32) */ \
SDOREPLY(0x1018, 0x01, 4, OD_VENDOR_ID), \
\
/* PDO parameters are in Object Dictionary */ \
\
/* RPDO communication parameters */ \
/* [0x1400,0x00] Receive PDO Parameter 1 - Highest Subindex Supported (Unsigned8) */ \
SDOREPLY(0x1400, 0x00, 1, 0x00000002L), \
/* [0x1400,0x01] Receive PDO Parameter 1 - COB ID used by PDO (Unsigned32) */ \
SDOREPLY(0x1400, 0x01, 4, 0x00000000L), \
/* [0x1400,0x02] Receive PDO Parameter 1 - Transmission Type (Unsigned8) */ \
SDOREPLY(0x1400, 0x02, 1, 0x000000FFL), \
/* [0x1400,0x03] Receive PDO Parameter 1 - Transmission Type (Unsigned8) */ \
SDOREPLY(0x1400, 0x03, 1, 0x000000FFL), \
\
/* RPDO mapping parameters */ \
/* [0x1600,0x00] Receive PDO Mapping 1 - Number of Entries (Unsigned8) */ \
SDOREPLY(0x1600, 0x00, 1, 0x00000002L), \
/* [0x1600,0x01] Receive PDO Mapping 1 - Target Velocity (Unsigned32) */ \
SDOREPLY(0x1600, 0x01, 4, 0x60FF0020L), \
/* [0x1600,0x02] Receive PDO Mapping 1 - Target Torque (Unsigned32) */ \
SDOREPLY(0x1600, 0x02, 4, 0x60710010L), \
/* [0x1600,0x03] Receive PDO Mapping 1 - Target Torque (Unsigned32) */ \
SDOREPLY(0x1600, 0x03, 4, 0x60710010L), \
\
/* TPDO communication parameters */ \
/* [0x1800,0x00] Transmit PDO Parameter 1 - Highest Subindex Supported (Unsigned8) */ \
SDOREPLY(0x1800, 0x00, 1, 0x00000005L), \
/* [0x1800,0x01] Transmit PDO Parameter 1 - COB ID used by PDO (Unsigned32) */ \
SDOREPLY(0x1800, 0x01, 4, 0x00000000L), \
/* [0x1800,0x02] Transmit PDO Parameter 1 - Transmission Type (Unsigned8) */ \
SDOREPLY(0x1800, 0x02, 1, 0x000000FFL), \
/* [0x1800,0x03] Transmit PDO Parameter 1 - Inhibit Time (Unsigned16) */ \
SDOREPLY(0x1800, 0x03, 2, 0x00000000L), \
/* [0x1800,0x04] Transmit PDO Parameter 1 - Compatibility Entry (Unsigned8) */ \
SDOREPLY(0x1800, 0x04, 1, 0x00000000L), \
/* [0x1800,0x05] Transmit PDO Parameter 1 - Event Timer (Unsigned16) */ \
SDOREPLY(0x1800, 0x05, 2, 0x00000000L), \
/* [0x1801,0x00] Transmit PDO Parameter 2 - Highest Subindex Supported (Unsigned8) */ \
SDOREPLY(0x1801, 0x00, 1, 0x00000005L), \
/* [0x1801,0x01] Transmit PDO Parameter 2 - COB ID used by PDO (Unsigned32) */ \
SDOREPLY(0x1801, 0x01, 4, 0x00000000L), \
/* [0x1801,0x02] Transmit PDO Parameter 2 - Transmission Type (Unsigned8) */ \
SDOREPLY(0x1801, 0x02, 1, 0x000000FFL), \
/* [0x1801,0x03] Transmit PDO Parameter 2 - Inhibit Time (Unsigned16) */ \
SDOREPLY(0x1801, 0x03, 2, 0x00000000L), \
/* [0x1801,0x04] Transmit PDO Parameter 2 - Compatibility Entry (Unsigned8) */ \
SDOREPLY(0x1801, 0x04, 1, 0x00000000L), \
/* [0x1801,0x05] Transmit PDO Parameter 2 - Event Timer (Unsigned16) */ \
SDOREPLY(0x1801, 0x05, 2, 0x00000000L), \
/* [0x1802,0x00] Transmit PDO Parameter 3 - Highest Subindex Supported (Unsigned8) */ \
SDOREPLY(0x1802, 0x00, 1, 0x00000005L), \
/* [0x1802,0x01] Transmit PDO Parameter 3 - COB ID used by PDO (Unsigned32) */ \
SDOREPLY(0x1802, 0x01, 4, 0x00000000L), \
/* [0x1802,0x02] Transmit PDO Parameter 3 - Transmission Type (Unsigned8) */ \
SDOREPLY(0x1802, 0x02, 1, 0x000000FFL), \
/* [0x1802,0x03] Transmit PDO Parameter 3 - Inhibit Time (Unsigned16) */ \
SDOREPLY(0x1802, 0x03, 2, 0x00000000L), \
/* [0x1802,0x04] Transmit PDO Parameter 3 - Compatibility Entry (Unsigned8) */ \
SDOREPLY(0x1802, 0x04, 1, 0x00000000L), \
/* [0x1802,0x05] Transmit PDO Parameter 3 - Event Timer (Unsigned16) */ \
SDOREPLY(0x1802, 0x05, 2, 0x00000000L), \
\
/* TPDO mapping parameters */ \
/* [0x1A00,0x00] Transmit PDO Mapping 1 - Number of Entries (Unsigned8) */ \
SDOREPLY(0x1A00, 0x00, 1, 0x00000002L), \
/* [0x1A00,0x01] Transmit PDO Mapping 1 - Status Word (Unsigned32) */ \
SDOREPLY(0x1A00, 0x01, 4, 0x60410010L), \
/* [0x1A00,0x02] Transmit PDO Mapping 1 - Modes of Operation Display (Unsigned32) */ \
SDOREPLY(0x1A00, 0x02, 4, 0x60610008L), \
/* [0x1A01,0x00] Transmit PDO Mapping 2 - Number of Entries (Unsigned8) */ \
SDOREPLY(0x1A01, 0x00, 1, 0x00000003L), \
/* [0x1A01,0x01] Transmit PDO Mapping 2 - Actual Velocity (Unsigned32) */ \
SDOREPLY(0x1A01, 0x01, 4, 0x606C0020L), \
/* [0x1A01,0x02] Transmit PDO Mapping 2 - Actual Torque (Unsigned32) */ \
SDOREPLY(0x1A01, 0x02, 4, 0x60770010L), \
/* [0x1A01,0x03] Transmit PDO Mapping 2 - Actual Motor Temperature (Unsigned32) */ \
SDOREPLY(0x1A01, 0x03, 4, 0x23010008L), \
/* [0x1A02,0x00] Transmit PDO Mapping 3 - Number of Entries (Unsigned8) */ \
SDOREPLY(0x1A02, 0x00, 1, 0x00000001L), \
/* [0x1A02,0x01] Transmit PDO Mapping 3 - Actual Position (Unsigned32) */ \
SDOREPLY(0x1A02, 0x01, 4, 0x60640020L), \
\
/* [0x1F50,0x00] Download Program Data - Number of Entries (Unsigned8) */ \
SDOREPLY(0x1F50, 0x00, 1, 0x00000001L), \
/* [0x1F51,0x00] Program Control - Number of Entries (Unsigned8) */ \
SDOREPLY(0x1F51, 0x00, 1, 0x00000001L), \
/* [0x1F51,0x01] Program Control - Control Program 1 (Unsigned8) */ \
SDOREPLY(0x1F51, 0x01, 1, 0x00000000L), \
/* [0x1F80,0x00] NMT Startup (Unsigned32) */ \
SDOREPLY(0x1F80, 0x00, 4, 0x00000000L), \

// 1 MACROS WERE GENERATED TO HOLD THE SDO REPLIES
// USE THE FOLLOWING INITIALIZER:
// SDOREPLY_ENTRIES 


#define ODGENTRY_CONSTINITS \
/* WARNING - ENTRY [1F50,01] SKIPPED AS DATA SIZE IS UNKNOWN */ \


#define ODGENTRY_ENTRIES \
/* WARNING - ENTRY [1F50,01] SKIPPED AS DATA SIZE IS UNKNOWN */ \

// 1 MACROS WERE GENERATED TO HOLD THE OD REPLIES
// USE THE FOLLOWING INITIALIZER:
// ODGENTRY_ENTRIES 

#define ODENTRY_ENTRIES \
/* mapping entries for RPDO1 [1600] */ \
ODENTRY(0x60FF, 0x00, 4+ODRD+ODWR+RMAP, P60FF00_TARGET_VELOCITY), \
ODENTRY(0x6071, 0x00, 2+ODRD+ODWR+RMAP, P607100_TARGET_TORQUE), \
ODENTRY(0x6071, 0x00, 2+ODRD+ODWR+RMAP, P607100_TARGET_TORQUE), \
/* mapping entries for TPDO1 [1A00] */ \
ODENTRY(0x6041, 0x00, 2+ODRD+RMAP, P604100_STATUS_WORD), \
ODENTRY(0x6061, 0x00, 1+ODRD+RMAP, P606100_MODES_OF_OPERATION_DISPLAY), \
/* mapping entries for TPDO2 [1A01] */ \
ODENTRY(0x606C, 0x00, 4+ODRD+RMAP, P606C00_ACTUAL_VELOCITY), \
ODENTRY(0x6077, 0x00, 2+ODRD+RMAP, P607700_ACTUAL_TORQUE), \
ODENTRY(0x2301, 0x00, 1+ODRD+RMAP, P230100_ACTUAL_MOTOR_TEMPERATURE), \
/* mapping entries for TPDO3 [1A02] */ \
ODENTRY(0x6064, 0x00, 4+ODRD+RMAP, P606400_ACTUAL_POSITION), \
ODENTRY(0x1001, 0x00, 1+ODRD+RMAP, P100100_ERROR_REGISTER), \
ODENTRY(0x1011, 0x01, 4+ODRD, P101101_RESTORE_ALL_PARAMETERS), \
ODENTRY(0x1011, 0x02, 4+ODRD, P101102_RESTORE_COMMUNICATION_PARAMETERS), \
ODENTRY(0x1011, 0x03, 4+ODRD, P101103_RESTORE_APPLICATION_PARAMETERS), \
ODENTRY(0x1011, 0x04, 4+ODRD, P101104_RESTORE_MANUFACTURER_DEFINED_PARAMETERS_1), \
ODENTRY(0x1015, 0x00, 2+ODRD+ODWR, P101500_EMERGENCY_INHIBIT_TIME), \
ODENTRY(0x1016, 0x01, 4+ODRD+ODWR, P101601_CONSUMER_HEARTBEAT_TIME_1), \
ODENTRY(0x1017, 0x00, 2+ODRD+ODWR, P101700_PRODUCER_HEARTBEAT_TIME), \
ODENTRY(0x1800, 0x03, 2+ODRD+ODWR, P180003_INHIBIT_TIME), \
ODENTRY(0x1800, 0x05, 2+ODRD+ODWR, P180005_EVENT_TIMER), \
ODENTRY(0x1801, 0x03, 2+ODRD+ODWR, P180103_INHIBIT_TIME), \
ODENTRY(0x1801, 0x05, 2+ODRD+ODWR, P180105_EVENT_TIMER), \
ODENTRY(0x1802, 0x03, 2+ODRD+ODWR, P180203_INHIBIT_TIME), \
ODENTRY(0x1802, 0x05, 2+ODRD+ODWR, P180205_EVENT_TIMER), \
/* WARNING - ENTRY [1F50,01] SKIPPED AS DATA SIZE IS UNKNOWN */ \
ODENTRY(0x6040, 0x00, 2+ODRD+ODWR, P604000_CONTROL_WORD), \
ODENTRY(0x6060, 0x00, 1+ODRD+ODWR, P606000_MODES_OF_OPERATION), \
ODENTRY(0x6072, 0x00, 2+ODRD+ODWR, P607200_MAXIMUM_TORQUE), \
ODENTRY(0x6075, 0x00, 4+ODRD+ODWR, P607500_MOTOR_RATED_CURRENT), \
ODENTRY(0x6076, 0x00, 4+ODRD+ODWR, P607600_MOTOR_RATED_TORQUE), \
ODENTRY(0x607A, 0x00, 4+ODRD+ODWR, P607A00_TARGET_POSITION), \
ODENTRY(0x607F, 0x00, 4+ODRD+ODWR, P607F00_MAXIMUM_PROFILE_VELOCITY), \
ODENTRY(0x6081, 0x00, 4+ODRD+ODWR, P608100_PROFILE_VELOCITY), \
ODENTRY(0x6083, 0x00, 4+ODRD+ODWR, P608300_PROFILE_ACCELERATION), \
ODENTRY(0x6084, 0x00, 4+ODRD+ODWR, P608400_PROFILE_DECELERATION), \
ODENTRY(0x6085, 0x00, 4+ODRD+ODWR, P608500_QUICK_STOP_DECELERATION), \
ODENTRY(0x6087, 0x00, 4+ODRD+ODWR, P608700_TORQUE_SLOPE), \

// 1 MACROS WERE GENERATED TO HOLD THE OD REPLIES
// USE THE FOLLOWING INITIALIZER:
// ODENTRY_ENTRIES 

#endif // _ENTRIESANDREPLIESH_
