// Process Image File
// Generated by CANopen Architect Standard 4.61.4043 on 3/12/2016 7:40:09 AM
// Generated from project C:\cd\ULC\build\ULC-build\NICBOT_MAIN_APP\APP\CANopen\MCO_NICBOTMAIN__User\EDS\NIC_Main.cax
// Generated from EDS 'NIC_Main' 01-27-2016 09:08AM by Unknown
// Use with MicroCANopen Plus CANopen stack
// For more information visit www.esacademy.com and www.microcanopen.com

// Check for warnings below before using this file

#ifndef _PIMGH_
#define _PIMGH_

// EDS configuration usage
// 1 = configuration was used when this file was generated
#define EDSCONFIGURATION_ALL_ENTRIES 1

// EDS group usage
// 1 = group was used when this file was generated

// set to 1 to use this stack config
#define AUTO_GENERATED_STACK_CONFIG 1

#if (AUTO_GENERATED_STACK_CONFIG == 1)
// stack configuration

// if no stack version defined then assume version 5.xx
#ifndef _MCOPVERSION_
#define _MCOPVERSION_ 5
#endif

// Maximum number of receive PDOs
#define NR_OF_RPDOS       1

// Maximum number of transmit PDOs
#define NR_OF_TPDOS       3

// Default Node ID of this node
#if _MCOPVERSION_ >= 6
#define NODEID_DCF        0x30
#define DEFAULT_EMCY_COBID 0x00000080L + NODEID_DCF
#else
#define NODE_ID           0x30
#define DEFAULT_EMCY_COBID 0x00000080L + NODE_ID
#endif

// device type
#define OD_DEVICE_TYPE    0xFFFF0192L

// Identity Object data [1018]
// Note: the values in Device -> Information are not used for this piece of code,
// only the values in [1018] are used
#define OD_VENDOR_ID      0x00000000L
#define OD_PRODUCT_CODE   0x00000000L
#define OD_REVISION       0x00000000L
#define OD_SERIAL_NUMBER  0x00000000L

// Specify the default heartbeat here
#define DEFAULT_HEARTBEAT 0

// Defines the maximum number of heartbeat consumers
#define NR_OF_HB_CONSUMER 1

// Defines the maximum number of emergency consumers
#define NR_OF_EMCY_CONSUMERS 0

// Defines the emergency inhibit time (x100us)
#define EMCY_INHIBIT_TIME 0

#endif // AUTO_GENERATED_STACK_CONFIG == 1

// [60FF,00] Integer32
#define P60FF00_TARGET_VELOCITY 0x00000000
// [6071,00] Integer16
#define P607100_TARGET_TORQUE 0x00000004
// [6041,00] Unsigned16
#define P604100_STATUS_WORD 0x00000008
// [6061,00] Integer8
#define P606100_MODES_OF_OPERATION_DISPLAY 0x0000000A
// [606C,00] Integer32
#define P606C00_ACTUAL_VELOCITY 0x0000000C
// [6077,00] Integer16
#define P607700_ACTUAL_TORQUE 0x00000010
// [2301,00] Unsigned8
#define P230100_ACTUAL_MOTOR_TEMPERATURE 0x00000012
// [6064,00] Integer32
#define P606400_ACTUAL_POSITION 0x00000014
// [1001,00] Unsigned8
#define P100100_ERROR_REGISTER 0x00000018
// [1011,01] Unsigned32
#define P101101_RESTORE_ALL_PARAMETERS 0x00000019
// [1011,02] Unsigned32
#define P101102_RESTORE_COMMUNICATION_PARAMETERS 0x0000001D
// [1011,03] Unsigned32
#define P101103_RESTORE_APPLICATION_PARAMETERS 0x00000021
// [1011,04] Unsigned32
#define P101104_RESTORE_MANUFACTURER_DEFINED_PARAMETERS_1 0x00000025
// [1015,00] Unsigned16
#define P101500_EMERGENCY_INHIBIT_TIME 0x00000029
// [1016,01] Unsigned32
#define P101601_CONSUMER_HEARTBEAT_TIME_1 0x0000002B
// [1017,00] Unsigned16
#define P101700_PRODUCER_HEARTBEAT_TIME 0x0000002F
// [1800,03] Unsigned16
#define P180003_INHIBIT_TIME 0x00000031
// [1800,05] Unsigned16
#define P180005_EVENT_TIMER 0x00000033
// [1801,03] Unsigned16
#define P180103_INHIBIT_TIME 0x00000035
// [1801,05] Unsigned16
#define P180105_EVENT_TIMER 0x00000037
// [1802,03] Unsigned16
#define P180203_INHIBIT_TIME 0x00000039
// [1802,05] Unsigned16
#define P180205_EVENT_TIMER 0x0000003B
// [6040,00] Unsigned16
#define P604000_CONTROL_WORD 0x0000003D
// [6060,00] Integer8
#define P606000_MODES_OF_OPERATION 0x0000003F
// [6072,00] Unsigned16
#define P607200_MAXIMUM_TORQUE 0x00000040
// [6075,00] Unsigned32
#define P607500_MOTOR_RATED_CURRENT 0x00000042
// [6076,00] Unsigned32
#define P607600_MOTOR_RATED_TORQUE 0x00000046
// [607A,00] Integer32
#define P607A00_TARGET_POSITION 0x0000004A
// [607F,00] Unsigned32
#define P607F00_MAXIMUM_PROFILE_VELOCITY 0x0000004E
// [6081,00] Unsigned32
#define P608100_PROFILE_VELOCITY 0x00000052
// [6083,00] Unsigned32
#define P608300_PROFILE_ACCELERATION 0x00000056
// [6084,00] Unsigned32
#define P608400_PROFILE_DECELERATION 0x0000005A
// [6085,00] Unsigned32
#define P608500_QUICK_STOP_DECELERATION 0x0000005E
// [6087,00] Unsigned32
#define P608700_TORQUE_SLOPE 0x00000062

// last byte used in process image
#define PIMGEND 0x00000065

// sizes for entries in the process image in bytes
#define SIZEOF_60FF_00_TARGET_VELOCITY 4
#define SIZEOF_6071_00_TARGET_TORQUE 2
#define SIZEOF_6041_00_STATUS_WORD 2
#define SIZEOF_6061_00_MODES_OF_OPERATION_DISPLAY 1
#define SIZEOF_606C_00_ACTUAL_VELOCITY 4
#define SIZEOF_6077_00_ACTUAL_TORQUE 2
#define SIZEOF_2301_00_ACTUAL_MOTOR_TEMPERATURE 1
#define SIZEOF_6064_00_ACTUAL_POSITION 4
#define SIZEOF_1001_00_ERROR_REGISTER 1
#define SIZEOF_1011_01_RESTORE_ALL_PARAMETERS 4
#define SIZEOF_1011_02_RESTORE_COMMUNICATION_PARAMETERS 4
#define SIZEOF_1011_03_RESTORE_APPLICATION_PARAMETERS 4
#define SIZEOF_1011_04_RESTORE_MANUFACTURER_DEFINED_PARAMETERS_1 4
#define SIZEOF_1015_00_EMERGENCY_INHIBIT_TIME 2
#define SIZEOF_1016_01_CONSUMER_HEARTBEAT_TIME_1 4
#define SIZEOF_1017_00_PRODUCER_HEARTBEAT_TIME 2
#define SIZEOF_1800_03_INHIBIT_TIME 2
#define SIZEOF_1800_05_EVENT_TIMER 2
#define SIZEOF_1801_03_INHIBIT_TIME 2
#define SIZEOF_1801_05_EVENT_TIMER 2
#define SIZEOF_1802_03_INHIBIT_TIME 2
#define SIZEOF_1802_05_EVENT_TIMER 2
#define SIZEOF_6040_00_CONTROL_WORD 2
#define SIZEOF_6060_00_MODES_OF_OPERATION 1
#define SIZEOF_6072_00_MAXIMUM_TORQUE 2
#define SIZEOF_6075_00_MOTOR_RATED_CURRENT 4
#define SIZEOF_6076_00_MOTOR_RATED_TORQUE 4
#define SIZEOF_607A_00_TARGET_POSITION 4
#define SIZEOF_607F_00_MAXIMUM_PROFILE_VELOCITY 4
#define SIZEOF_6081_00_PROFILE_VELOCITY 4
#define SIZEOF_6083_00_PROFILE_ACCELERATION 4
#define SIZEOF_6084_00_PROFILE_DECELERATION 4
#define SIZEOF_6085_00_QUICK_STOP_DECELERATION 4
#define SIZEOF_6087_00_TORQUE_SLOPE 4

// default values for process image
#define PIMGDEFAULTS { \
/*[60FF,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[6071,00]*/        0x00, 0x00, \
/* padding */        0x00, 0x00, \
/*[6041,00]*/        0x00, 0x00, \
/*[6061,00]*/        0x00, \
/* padding */        0x00, \
/*[606C,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[6077,00]*/        0x00, 0x00, \
/*[2301,00]*/        0x00, \
/* padding */        0x00, \
/*[6064,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1001,00]*/        0x00, \
/*[1011,01]*/        0x00, 0x00, 0x00, 0x00, \
/*[1011,02]*/        0x00, 0x00, 0x00, 0x00, \
/*[1011,03]*/        0x00, 0x00, 0x00, 0x00, \
/*[1011,04]*/        0x00, 0x00, 0x00, 0x00, \
/*[1015,00]*/        0x00, 0x00, \
/*[1016,01]*/        0x00, 0x00, 0x00, 0x00, \
/*[1017,00]*/        0x00, 0x00, \
/*[1800,03]*/        0x00, 0x00, \
/*[1800,05]*/        0x00, 0x00, \
/*[1801,03]*/        0x00, 0x00, \
/*[1801,05]*/        0x00, 0x00, \
/*[1802,03]*/        0x00, 0x00, \
/*[1802,05]*/        0x00, 0x00, \
/*[6040,00]*/        0x00, 0x00, \
/*[6060,00]*/        0x00, \
/*[6072,00]*/        0x00, 0x00, \
/*[6075,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[6076,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[607A,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[607F,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[6081,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[6083,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[6084,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[6085,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[6087,00]*/        0x00, 0x00, 0x00, 0x00, \
                     }

// 1 MACROS WERE GENERATED TO HOLD THE PROCESS IMAGE
// USE THE FOLLOWING INITIALIZER:
// PIMGDEFAULTS 

// minimum values for process image
#define PIMGMINS { \
/*[60FF,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[6071,00]*/        0x00, 0x00, \
/* padding */        0x00, 0x00, \
/*[6041,00]*/        0x00, 0x00, \
/*[6061,00]*/        0x00, \
/* padding */        0x00, \
/*[606C,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[6077,00]*/        0x00, 0x00, \
/*[2301,00]*/        0x00, \
/* padding */        0x00, \
/*[6064,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1001,00]*/        0x00, \
/*[1011,01]*/        0x00, 0x00, 0x00, 0x00, \
/*[1011,02]*/        0x00, 0x00, 0x00, 0x00, \
/*[1011,03]*/        0x00, 0x00, 0x00, 0x00, \
/*[1011,04]*/        0x00, 0x00, 0x00, 0x00, \
/*[1015,00]*/        0x00, 0x00, \
/*[1016,01]*/        0x00, 0x00, 0x00, 0x00, \
/*[1017,00]*/        0x00, 0x00, \
/*[1800,03]*/        0x00, 0x00, \
/*[1800,05]*/        0x00, 0x00, \
/*[1801,03]*/        0x00, 0x00, \
/*[1801,05]*/        0x00, 0x00, \
/*[1802,03]*/        0x00, 0x00, \
/*[1802,05]*/        0x00, 0x00, \
/*[6040,00]*/        0x00, 0x00, \
/*[6060,00]*/        0x00, \
/*[6072,00]*/        0x00, 0x00, \
/*[6075,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[6076,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[607A,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[607F,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[6081,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[6083,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[6084,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[6085,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[6087,00]*/        0x00, 0x00, 0x00, 0x00, \
                     }

// 1 MACROS WERE GENERATED TO HOLD THE PROCESS IMAGE
// USE THE FOLLOWING INITIALIZER:
// PIMGMINS 

// maximum values for process image
#define PIMGMAXS { \
/*[60FF,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[6071,00]*/        0x00, 0x00, \
/* padding */        0x00, 0x00, \
/*[6041,00]*/        0x00, 0x00, \
/*[6061,00]*/        0x00, \
/* padding */        0x00, \
/*[606C,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[6077,00]*/        0x00, 0x00, \
/*[2301,00]*/        0x00, \
/* padding */        0x00, \
/*[6064,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1001,00]*/        0x00, \
/*[1011,01]*/        0x00, 0x00, 0x00, 0x00, \
/*[1011,02]*/        0x00, 0x00, 0x00, 0x00, \
/*[1011,03]*/        0x00, 0x00, 0x00, 0x00, \
/*[1011,04]*/        0x00, 0x00, 0x00, 0x00, \
/*[1015,00]*/        0x00, 0x00, \
/*[1016,01]*/        0x00, 0x00, 0x00, 0x00, \
/*[1017,00]*/        0x00, 0x00, \
/*[1800,03]*/        0x00, 0x00, \
/*[1800,05]*/        0x00, 0x00, \
/*[1801,03]*/        0x00, 0x00, \
/*[1801,05]*/        0x00, 0x00, \
/*[1802,03]*/        0x00, 0x00, \
/*[1802,05]*/        0x00, 0x00, \
/*[6040,00]*/        0x00, 0x00, \
/*[6060,00]*/        0x00, \
/*[6072,00]*/        0x00, 0x00, \
/*[6075,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[6076,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[607A,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[607F,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[6081,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[6083,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[6084,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[6085,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[6087,00]*/        0x00, 0x00, 0x00, 0x00, \
                     }

// 1 MACROS WERE GENERATED TO HOLD THE PROCESS IMAGE
// USE THE FOLLOWING INITIALIZER:
// PIMGMAXS 

#endif // _PIMGH_
