// Initialization
// Generated by CANopen Architect Standard 4.61.4043 on 3/16/2016 8:17:04 PM
// Generated from project C:\cd\ULC\build\ULC-build\NICBOT_MAIN_APP\APP\CANopen\MCO_NICBOTMAIN__User\EDS\NIC_Main.cax
// Generated from EDS 'NIC_Main' 01-27-2016 09:08AM by Unknown
// Use with MicroCANopen Plus CANopen stack
// For more information visit www.esacademy.com and www.microcanopen.com

// Check for warnings below before using this file

#ifndef _STACKINITH_
#define _STACKINITH_

// CAN bitrate definitions as defined in CiA305
#define CIA305_CAN_BITRATE_1000 0
#define CIA305_CAN_BITRATE_800  1
#define CIA305_CAN_BITRATE_500  2
#define CIA305_CAN_BITRATE_250  3
#define CIA305_CAN_BITRATE_125  4
#define CIA305_CAN_BITRATE_50   6
#define CIA305_CAN_BITRATE_20   7
#define CIA305_CAN_BITRATE_10   8
#define CIA305_CAN_BITRATE_AUTO 9

// CAN bitrates supported by this device
#define CAN_BITRATE_SUPPORTED ( \
  (1U << CIA305_CAN_BITRATE_50  )   \
)

// Default CAN bitrate (kbps)
#define CAN_BITRATE_DCF 50

#define INITPDOS_CALLS \
MCO_InitRPDO(1, NODEID+0x00000200, 8, P60FF00_TARGET_VELOCITY); \
MCO_InitTPDOFull(1, NODEID+0x00000180, 0, 0, 255, 3, P604100_STATUS_WORD); \
MCO_InitTPDOFull(2, NODEID+0x00000280, 0, 0, 255, 7, P606C00_ACTUAL_VELOCITY); \
MCO_InitTPDOFull(3, NODEID+0x00000380, 0, 0, 255, 4, P606400_ACTUAL_POSITION); \

#define INITHBCONSUMER_CALLS \
/* WARNING - NODE ID 0x00 IS INVALID FOR ENTRY [1016,01] */ \

#define INITEMCYCONSUMER_CALLS \

#endif // _STACKINITH_
